// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApUJdKXiRqFhbvslTi5cHix20Jn6O6b0c',
    appId: '1:635670337807:web:57c745af0f1b7444cd467a',
    messagingSenderId: '635670337807',
    projectId: 'crg-scratch-022423',
    authDomain: 'crg-scratch-022423.firebaseapp.com',
    storageBucket: 'crg-scratch-022423.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2z5YFSG5r-lk8XBJIGyp1ASBdRzTCVNg',
    appId: '1:635670337807:android:d511b69bc94492b9cd467a',
    messagingSenderId: '635670337807',
    projectId: 'crg-scratch-022423',
    storageBucket: 'crg-scratch-022423.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt5z-TCoYVuxMNnsNoqSYWE6h9dF0OOyg',
    appId: '1:635670337807:ios:6dd722b519f630a8cd467a',
    messagingSenderId: '635670337807',
    projectId: 'crg-scratch-022423',
    storageBucket: 'crg-scratch-022423.appspot.com',
    iosClientId: '635670337807-j6ukh32ufdtvlqp7ime81k0h6hfr8sb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.summarize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt5z-TCoYVuxMNnsNoqSYWE6h9dF0OOyg',
    appId: '1:635670337807:ios:4411e8d958688185cd467a',
    messagingSenderId: '635670337807',
    projectId: 'crg-scratch-022423',
    storageBucket: 'crg-scratch-022423.appspot.com',
    iosClientId: '635670337807-enkqldipm6t9cs5esclij4s9uelim5vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.summarize.RunnerTests',
  );
}
